# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-26 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('witlof', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentattachment',
            name='attachment',
            field=models.FileField(max_length=500, upload_to=b'witlof/attachments/%Y/%m/%d/%H/%M/%S/'),
        ),
        migrations.AlterField(
            model_name='documentimage',
            name='image',
            field=models.ImageField(height_field=b'height', max_length=500, upload_to=b'witlof/images/%Y/%m/%d/%H/%M/%S/', width_field=b'width'),
        ),
    ]
